# Generated by Django 4.1.7 on 2023-02-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('is_paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.TextField(max_length=100)),
                ('u_description', models.TextField()),
                ('u_video', models.FileField(upload_to='video/%y')),
                ('u_image', models.ImageField(upload_to='unit-image/')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classhub.subject')),
            ],
        ),
    ]
